// GENERATED — 손으로 편집하지 마세요. 재생성: node scripts/gen-registry.mjs
// SSOT: scripts/harness.mjs · .claude/{agents,skills}/ · src/ui/screens/ · supabase/migrations/ · src/app/{changelog,researchLog}.ts
// check-registry-gen 게이트가 이 파일이 SSOT와 일치하는지(커밋본==재생성본) 검사합니다.

export const REGISTRY = {
  /** npm run harness가 도는 Required 게이트 이름(정본: scripts/harness.mjs). */
  gates: [
  'typecheck',
  'check-secret-leak',
  'check-hooks-wired',
  'check-ci-policy',
  'check-workflow-pins',
  'check-dependabot-policy',
  'check-shared-skill-contract',
  'check-input-closeout',
  'check-gate-promise',
  'check-env-assumption',
  'check-live-sleep',
  'check-doc-tree',
  'check-step-duration',
  'check-recovery-path',
  'check-review-tier',
  'check-domain-wiring',
  'check-csp',
  'check-production-artifacts',
  'check-base-consistency',
  'check-env-wiring',
  'check-domain-symmetry',
  'check-sync-parallelism',
  'check-verdict-symmetry',
  'check-reduced-motion-scope',
  'check-skill-routing',
  'check-live-coverage',
  'check-self-eval',
  'check-schema-parity',
  'check-migration-grants',
  'check-report-fields',
  'check-no-synthetic-italic',
  'check-edge-fn-ops',
  'check-sync-release-contract',
  'check-node-version',
  'check-backup-coverage',
  'check-blueprint',
  'check-registry-gen',
  'check-constitution-gen',
  'check-adapter-parity',
  'check-doc-governance',
  'check-doc-references',
  'check-module-design-docs',
  'check-gate-integrity',
  'check-diag-blindspots',
  'check-page-size-parity',
  'check-current-doc-facts',
  'check-platform-map',
  'check-lazy-screens',
  'check-font-subsets',
  'check-fn-size',
  'check-sw',
  'check-hand-counts',
  'check-doc-counts',
  'check-date-freshness',
  'check-version-ssot',
  'check-screen-lifecycle',
  'check-timezone',
  'check-instant-normalization',
  'check-exif-strip-on-share',
  'check-exif-order',
  'check-bytes-upload-symmetry',
  'check-known-index',
  'check-apk-release-link',
  'check-windows-shell',
  'check-update-signal',
  'check-purge-scope',
  'check-real-coord',
  'check-edge-cors',
  'check-gate-control',
  'check-enforcement-parity',
  'check-tooling-registry',
  'check-ui-color-token',
  'unit-tests',
  'verify-editor-live',
  'verify-diagnostics-live',
  'verify-authgate-live',
  ] as const,
  gateCount: 76,
  /**
   * 게이트의 **대조군 현황**(§4). 세 축 — 대조군 보유 · 밖에서 돌려 볼 수 있음 ·
   * 실패를 판정(exit 2)으로 알림.
   *
   * 🔴 **이것은 「검사가 통과했다」가 아니다.** 앱은 게이트가 실제로 돌았는지 **볼 수 없다**
   *    (CI는 앱 밖이다 · diagGroups의 ERRORS-GATE-HEALTH). 여기 있는 값은 **저장소에 적힌
   *    계약**이고, 화면도 반드시 그렇게 말해야 한다 — 앱이 판정하는 척하면 그 초록이 거짓이 된다(§8).
   */
  gateControl: [
    { name: 'check-secret-leak', control: true, runnable: true, cleanExit: true },
    { name: 'check-hooks-wired', control: true, runnable: false, cleanExit: true },
    { name: 'check-ci-policy', control: true, runnable: false, cleanExit: true },
    { name: 'check-workflow-pins', control: true, runnable: true, cleanExit: true },
    { name: 'check-dependabot-policy', control: true, runnable: true, cleanExit: true },
    { name: 'check-shared-skill-contract', control: true, runnable: false, cleanExit: true },
    { name: 'check-input-closeout', control: true, runnable: false, cleanExit: true },
    { name: 'check-gate-promise', control: true, runnable: false, cleanExit: true },
    { name: 'check-env-assumption', control: true, runnable: false, cleanExit: true },
    { name: 'check-live-sleep', control: true, runnable: false, cleanExit: true },
    { name: 'check-doc-tree', control: true, runnable: false, cleanExit: true },
    { name: 'check-step-duration', control: true, runnable: false, cleanExit: true },
    { name: 'check-recovery-path', control: true, runnable: false, cleanExit: true },
    { name: 'check-review-tier', control: true, runnable: false, cleanExit: true },
    { name: 'check-domain-wiring', control: true, runnable: false, cleanExit: true },
    { name: 'check-csp', control: true, runnable: false, cleanExit: true },
    { name: 'check-production-artifacts', control: true, runnable: true, cleanExit: true },
    { name: 'check-base-consistency', control: true, runnable: false, cleanExit: true },
    { name: 'check-env-wiring', control: true, runnable: false, cleanExit: true },
    { name: 'check-domain-symmetry', control: true, runnable: false, cleanExit: true },
    { name: 'check-sync-parallelism', control: true, runnable: true, cleanExit: true },
    { name: 'check-verdict-symmetry', control: true, runnable: false, cleanExit: true },
    { name: 'check-reduced-motion-scope', control: true, runnable: false, cleanExit: true },
    { name: 'check-skill-routing', control: true, runnable: false, cleanExit: true },
    { name: 'check-live-coverage', control: true, runnable: false, cleanExit: true },
    { name: 'check-self-eval', control: true, runnable: false, cleanExit: true },
    { name: 'check-schema-parity', control: true, runnable: false, cleanExit: true },
    { name: 'check-migration-grants', control: true, runnable: false, cleanExit: true },
    { name: 'check-report-fields', control: true, runnable: false, cleanExit: true },
    { name: 'check-no-synthetic-italic', control: true, runnable: false, cleanExit: true },
    { name: 'check-edge-fn-ops', control: true, runnable: false, cleanExit: true },
    { name: 'check-sync-release-contract', control: true, runnable: false, cleanExit: true },
    { name: 'check-node-version', control: true, runnable: false, cleanExit: true },
    { name: 'check-backup-coverage', control: true, runnable: true, cleanExit: true },
    { name: 'check-blueprint', control: true, runnable: true, cleanExit: true },
    { name: 'check-registry-gen', control: true, runnable: false, cleanExit: true },
    { name: 'check-constitution-gen', control: true, runnable: false, cleanExit: true },
    { name: 'check-adapter-parity', control: true, runnable: false, cleanExit: true },
    { name: 'check-doc-governance', control: true, runnable: false, cleanExit: true },
    { name: 'check-doc-references', control: true, runnable: true, cleanExit: true },
    { name: 'check-module-design-docs', control: true, runnable: false, cleanExit: true },
    { name: 'check-gate-integrity', control: true, runnable: false, cleanExit: true },
    { name: 'check-diag-blindspots', control: true, runnable: false, cleanExit: true },
    { name: 'check-page-size-parity', control: true, runnable: false, cleanExit: true },
    { name: 'check-current-doc-facts', control: true, runnable: true, cleanExit: true },
    { name: 'check-platform-map', control: true, runnable: false, cleanExit: true },
    { name: 'check-lazy-screens', control: true, runnable: false, cleanExit: true },
    { name: 'check-font-subsets', control: true, runnable: false, cleanExit: true },
    { name: 'check-fn-size', control: true, runnable: false, cleanExit: true },
    { name: 'check-sw', control: true, runnable: false, cleanExit: true },
    { name: 'check-hand-counts', control: true, runnable: false, cleanExit: true },
    { name: 'check-doc-counts', control: true, runnable: false, cleanExit: true },
    { name: 'check-date-freshness', control: true, runnable: true, cleanExit: true },
    { name: 'check-version-ssot', control: true, runnable: true, cleanExit: true },
    { name: 'check-screen-lifecycle', control: true, runnable: false, cleanExit: true },
    { name: 'check-timezone', control: true, runnable: false, cleanExit: true },
    { name: 'check-instant-normalization', control: true, runnable: false, cleanExit: true },
    { name: 'check-exif-strip-on-share', control: true, runnable: false, cleanExit: true },
    { name: 'check-exif-order', control: true, runnable: false, cleanExit: true },
    { name: 'check-bytes-upload-symmetry', control: true, runnable: false, cleanExit: true },
    { name: 'check-known-index', control: true, runnable: false, cleanExit: true },
    { name: 'check-apk-release-link', control: true, runnable: true, cleanExit: true },
    { name: 'check-windows-shell', control: true, runnable: false, cleanExit: true },
    { name: 'check-update-signal', control: true, runnable: true, cleanExit: true },
    { name: 'check-purge-scope', control: true, runnable: true, cleanExit: true },
    { name: 'check-real-coord', control: true, runnable: true, cleanExit: true },
    { name: 'check-edge-cors', control: true, runnable: true, cleanExit: true },
    { name: 'check-gate-control', control: true, runnable: true, cleanExit: true },
    { name: 'check-enforcement-parity', control: true, runnable: true, cleanExit: true },
    { name: 'check-tooling-registry', control: true, runnable: true, cleanExit: true },
    { name: 'check-ui-color-token', control: true, runnable: false, cleanExit: true },
    { name: 'verify-editor-live', control: true, runnable: false, cleanExit: true },
    { name: 'verify-diagnostics-live', control: true, runnable: false, cleanExit: true },
    { name: 'verify-authgate-live', control: true, runnable: false, cleanExit: true },
    { name: 'verify-sync-release-live', control: true, runnable: false, cleanExit: true },
  ] as const,
  gateControlCount: 75,
  gateRunnableCount: 19,
  gateCleanExitCount: 75,
  /** 최신 앱 버전(정본: src/app/changelog.ts의 첫 항목). 첫 로드 화면은 이걸 읽는다. */
  appVersion: '2.47',
  /** 에이전트 정의 이름(정본: .claude/agents/ — frontmatter가 있는 파일만). */
  agents: [
  'accessibility-design-auditor',
  'adversarial-visual-reviewer',
  'design-consistency-auditor',
  'design-token-sync-agent',
  'disaster-recovery-guardian',
  'emotional-visual-director',
  'empty-state-designer',
  'figma-handoff-agent',
  'frontend',
  'map-experience-designer',
  'media-pipeline',
  'memory-centered-ux',
  'mobile-capture-ux',
  'mobile-device-design-auditor',
  'motion-interaction-designer',
  'offline-sync',
  'orchestrator',
  'photo-storytelling-designer',
  'product-ux',
  'qa',
  'reviewer-release',
  'security-privacy',
  'supabase',
  'timeline-interaction-designer',
  'travel-design-system',
  'travel-domain',
  'travel-experience-director',
  ] as const,
  agentCount: 27,
  /** docs/AGENT_REGISTRY.md의 논리 역할 수. 가이드가 손으로 「139개」를 적지 않게. */
  logicalRoleCount: 139,
  skillCount: 13,
  screenCount: 13,
  migrationCount: 32,
  changelogCount: 247,
  researchCount: 144,
} as const;
