// GENERATED — 손으로 편집하지 마세요. 재생성: node scripts/gen-registry.mjs
// SSOT: scripts/harness.mjs · .claude/{agents,skills}/ · src/ui/screens/ · supabase/migrations/ · src/app/{changelog,researchLog}.ts
// check-registry-gen 게이트가 이 파일이 SSOT와 일치하는지(커밋본==재생성본) 검사합니다.

export const REGISTRY = {
  /** npm run harness가 도는 Required 게이트 이름(정본: scripts/harness.mjs). */
  gates: [
  'typecheck',
  'check-secret-leak',
  'check-domain-wiring',
  'check-csp',
  'check-base-consistency',
  'check-env-wiring',
  'check-domain-symmetry',
  'check-verdict-symmetry',
  'check-skill-routing',
  'check-live-coverage',
  'check-self-eval',
  'check-schema-parity',
  'check-migration-grants',
  'check-report-fields',
  'check-no-synthetic-italic',
  'check-edge-fn-ops',
  'check-node-version',
  'check-backup-coverage',
  'check-blueprint',
  'check-registry-gen',
  'check-adapter-parity',
  'check-doc-governance',
  'check-platform-map',
  'check-lazy-screens',
  'check-font-subsets',
  'check-fn-size',
  'check-sw',
  'check-hand-counts',
  'check-doc-counts',
  'check-timezone',
  'check-instant-normalization',
  'check-exif-strip-on-share',
  'unit-tests',
  'verify-editor-live',
  'verify-diagnostics-live',
  ] as const,
  gateCount: 35,
  /** 최신 앱 버전(정본: src/app/changelog.ts의 첫 항목). 첫 로드 화면은 이걸 읽는다. */
  appVersion: '1.23',
  agentCount: 28,
  skillCount: 9,
  screenCount: 11,
  migrationCount: 21,
  changelogCount: 123,
  researchCount: 59,
} as const;
