// GENERATED — 손으로 편집하지 마세요. 재생성: node scripts/gen-registry.mjs
// SSOT: scripts/harness.mjs · .claude/{agents,skills}/ · src/ui/screens/ · supabase/migrations/ · src/app/{changelog,researchLog}.ts
// check-registry-gen 게이트가 이 파일이 SSOT와 일치하는지(커밋본==재생성본) 검사합니다.

export const REGISTRY = {
  /** npm run harness가 도는 Required 게이트 이름(정본: scripts/harness.mjs). */
  gates: [
  'typecheck',
  'check-secret-leak',
  'check-hooks-wired',
  'check-ci-policy',
  'check-domain-wiring',
  'check-csp',
  'check-base-consistency',
  'check-env-wiring',
  'check-domain-symmetry',
  'check-verdict-symmetry',
  'check-skill-routing',
  'check-live-coverage',
  'check-self-eval',
  'check-schema-parity',
  'check-migration-grants',
  'check-report-fields',
  'check-no-synthetic-italic',
  'check-edge-fn-ops',
  'check-node-version',
  'check-backup-coverage',
  'check-blueprint',
  'check-registry-gen',
  'check-constitution-gen',
  'check-adapter-parity',
  'check-doc-governance',
  'check-platform-map',
  'check-lazy-screens',
  'check-font-subsets',
  'check-fn-size',
  'check-sw',
  'check-hand-counts',
  'check-doc-counts',
  'check-timezone',
  'check-instant-normalization',
  'check-exif-strip-on-share',
  'check-exif-order',
  'check-bytes-upload-symmetry',
  'check-known-index',
  'check-apk-release-link',
  'check-update-signal',
  'check-purge-scope',
  'check-real-coord',
  'check-ui-color-token',
  'unit-tests',
  'verify-editor-live',
  'verify-diagnostics-live',
  ] as const,
  gateCount: 46,
  /** 최신 앱 버전(정본: src/app/changelog.ts의 첫 항목). 첫 로드 화면은 이걸 읽는다. */
  appVersion: '1.68',
  /** 에이전트 정의 이름(정본: .claude/agents/ — frontmatter가 있는 파일만). */
  agents: [
  'accessibility-design-auditor',
  'adversarial-visual-reviewer',
  'design-consistency-auditor',
  'design-token-sync-agent',
  'disaster-recovery-guardian',
  'emotional-visual-director',
  'empty-state-designer',
  'figma-handoff-agent',
  'frontend',
  'map-experience-designer',
  'media-pipeline',
  'memory-centered-ux',
  'mobile-capture-ux',
  'mobile-device-design-auditor',
  'motion-interaction-designer',
  'offline-sync',
  'orchestrator',
  'photo-storytelling-designer',
  'product-ux',
  'qa',
  'reviewer-release',
  'security-privacy',
  'supabase',
  'timeline-interaction-designer',
  'travel-design-system',
  'travel-domain',
  'travel-experience-director',
  ] as const,
  agentCount: 27,
  /** docs/AGENT_REGISTRY.md의 논리 역할 수. 가이드가 손으로 「139개」를 적지 않게. */
  logicalRoleCount: 139,
  skillCount: 11,
  screenCount: 11,
  migrationCount: 28,
  changelogCount: 168,
  researchCount: 76,
} as const;
