// app/researchLog.ts — 연구노트(특허 증거용) 데이터의 단일 진실원(SSOT).
//
// 이 앱을 만들며 "사람이 생각하고 결정한 흔적"을 사람/AI/최종결정 3단으로 남긴다.
// AI가 도왔지만 방향·판단·최종결정은 사람이 했다는 구조화 기록이다(app/hashchain.ts로 해시체인).
// 정직성(§4): 여기 적힌 건 실제 세션에서 오간 결정만이다. 새 항목은 배열 끝에 append(순서·seq 불변).

import type { ChainInput } from './hashchain';

/** 연구노트 항목. seq는 append-only 순번(재배열 금지 — 해시체인이 순서에 의존). */
export const RESEARCH_LOG: ChainInput[] = [
  {
    seq: 1,
    date: '2026-07-22',
    topic: '기술 스택 — 프레임워크 없이 갈까',
    human: '개인 여행기록 앱을 오프라인 우선으로. 무겁지 않게.',
    ai: 'Vanilla TS + Vite + Dexie(IndexedDB) + Supabase를 제안. MVP에서 프레임워크 추가 안 함.',
    decision: 'Vanilla TS 구조 채택. 실제 유지불가로 측정될 때만 기술변경 제안서를 쓴다(CLAUDE.md).',
  },
  {
    seq: 2,
    date: '2026-07-22',
    topic: '데이터 안전 — 기억을 잃지 않기',
    human: '기록한 여행 기억은 절대 잃으면 안 된다.',
    ai: '내구성 로컬 커밋(entity+operation atomic)+read-back, tombstone(하드삭제 없음), LWW, 빈-클라우드 가드를 제안.',
    decision: '로컬 커밋 이후 앱 원인 유실 0을 비타협 원칙으로 못박음(SYNC_PROTOCOL).',
  },
  {
    seq: 3,
    date: '2026-07-23',
    topic: '저장된 기록을 못 고침',
    human: '이미 저장된 순간·사진이 편집·삭제가 안 된다.',
    ai: '순간 편집/삭제 + 사진 개별 삭제를 tombstone·실행취소(undo)로 제안(복구 가능성 우선).',
    decision: '편집/삭제를 복구 가능한 형태로 구현. 원본 사진은 기기에서 변경/삭제하지 않음(§0).',
  },
  {
    seq: 4,
    date: '2026-07-23',
    topic: '코딩 규율을 헌법에',
    human: '코딩할 때 항상 육하원칙(5W1H)을 생각하도록 헌법에 박아두자.',
    ai: '왜/무엇을/어디서/언제/누가/어떻게를 착수 전·중 자문하는 Pre-flight 5W1H를 CLAUDE.md에 삽입 제안.',
    decision: '5W1H를 결함 예방 장치로 헌법에 명문화. 답이 서로 모순되면 멈추고 재설계.',
  },
  {
    seq: 5,
    date: '2026-07-23',
    topic: '장소 — 구글맵인가 무료맵인가',
    human: '장소는 구글맵 또는 다른 무료 맵을 못 쓰나?',
    ai: '구글맵은 API 키·결제 필요. OSM 타일과 일관된 무료·키 불필요의 Nominatim 지오코딩을 제안.',
    decision: 'Nominatim 채택. 검색은 버튼 제출 시에만(저트래픽·귀속), 결과는 textContent로만 렌더(XSS 방지).',
  },
  {
    seq: 6,
    date: '2026-07-23',
    topic: '제목 자간이 기기마다 갈라짐',
    human: '제목 연도 숫자 자간이 갈라진다. 맑은고딕으로 픽스하면?',
    ai: '맑은고딕은 Windows 전용이라 안드로이드에 없음. 기기 독립적인 Pretendard 웹폰트 번들을 제안.',
    decision: 'Pretendard woff2를 앱에 번들(self-host). 모든 기기에서 동일 렌더로 자간 문제 확정 해결.',
  },
  {
    seq: 7,
    date: '2026-07-23',
    topic: '선택 후 검색창이 안 사라짐',
    human: '장소를 선택하면 선택창이 사라져야 하는 것 아닌가?',
    ai: 'display를 가진 클래스가 [hidden] 속성을 이기는 CSS 결함군으로 진단. 전역 [hidden]{display:none!important} 제안.',
    decision: '단건 수정이 아니라 결함군으로 승격해 전역 박멸(형제 위치 일괄).',
  },
  {
    seq: 8,
    date: '2026-07-23',
    topic: '등록되지 않은 장소',
    human: '지도에서도 위치를 지정하고, 등록 안 된 곳은 이름을 직접 적게 하자.',
    ai: '지도 탭-투-픽(마커 드래그) + 이름·좌표 독립 입력을 제안(mapPicked 플래그로 이름 입력 시 좌표 유지).',
    decision: '지도 위치 지정 + 자유 이름 입력 채택. 검색 좌표는 이름과 묶고, 지도 좌표는 독립.',
  },
  {
    seq: 9,
    date: '2026-07-23',
    topic: '세로 사진 편집 화질·크롭',
    human: '세로 사진이 작게 뜨고 여백이 크다. 자르기 적용 버튼도 안 보인다.',
    ai: '폭 맞추기 + 미리보기 해상도 상향, 이미지 아래 크롭 확정 버튼, 폭 100%(세로 스크롤) 선택 옵션을 제안.',
    decision: '폭 맞춤/폭 채우기 선택 + 크롭 확정 버튼 채택. 두 방식 모두 크롭 오버레이 정렬 보장.',
  },
  {
    seq: 10,
    date: '2026-07-23',
    topic: '버전·개발자 정보·법령 체계',
    human: '버전을 0.00부터 0.01씩 올리고, 메디컬 앱처럼 개발자 정보·이력·법령 체계를 넣자.',
    ai: 'PR 병합=릴리스로 소급 버전 부여, changelog SSOT, 문서 지도를 규범 위계로 재구성 제안.',
    decision: 'src/app/changelog.ts를 버전 SSOT로. 개발자 정보 화면 + 문서 규범 체계 5단 시각화 채택.',
  },
  {
    seq: 11,
    date: '2026-07-23',
    topic: '연구노트(특허 증거용)',
    human: '메디컬 앱처럼 연구노트(사람/AI/최종결정 흔적·해시체인)를 넣자.',
    ai: 'ChainInput을 SHA-256으로 append-only 체인화(Web Crypto), 앵커 해시로 위·변조 감지를 제안.',
    decision: '연구노트 채택. 법적 보증이 아니라 특허 검토용 구조화 증거 로그로 명확히 표기(과장 금지).',
  },
  {
    seq: 12,
    date: '2026-07-23',
    topic: '편집 미리보기 잘림·확대 제스처',
    human: '편집기에서 세로 사진이 잘려 회전을 확인할 수 없다. 핀치 확대와 PC Ctrl+휠 확대도 필요하다.',
    ai: '잘림 원인을 overflow:hidden flex 자식의 최소크기 0 압착으로 진단(M-flex-clip). 수축 금지 + Ctrl+휠 줌(트랙패드 핀치 포함) 제안. 두 손가락 핀치는 v0.24에 이미 존재.',
    decision: '스테이지 수축 금지로 잘림 해결, Ctrl+휠 줌 추가(연속 제스처 undo 규칙 준수). 결함은 헌장 결함 등록부에 기록.',
  },
  {
    seq: 13,
    date: '2026-07-23',
    topic: '저장된 순간에 사진 추가·배치 장수',
    human: '편집 상태에서 사진 추가 기능이 없다. 한 번에 몇 장까지 저장되나?',
    ai: '생성 흐름의 배치 처리를 processPhotosIntoMoment 단일 함수로 추출해 편집 모드에 재사용 제안. 장수 제한은 없음(순차 처리라 메모리는 장당 한 장).',
    decision: '편집(✎) 시 “📷 사진 추가” 노출. 배치 경로 SSOT화(생성·추가 공유). 명시적 상한 두지 않음.',
  },
  {
    seq: 14,
    date: '2026-07-23',
    topic: '표시본 품질과 저장 용량 가시화',
    human: '사진 품질을 올리자. 그리고 저장 용량을 사진/텍스트로 나눠 볼 수 있게 하자. 용량은 얼마나 늘어나나?',
    ai: '12MP급 실측: 표시본 1600px q0.82(~0.47MB) vs q0.90(~0.66MB, +40%) vs 2048/q0.90(~2.2×). 크기 유지+품질만 상향과 사진/텍스트 용량 분리 표시를 제안.',
    decision: '표시본 품질 0.82→0.90(크기 1600 유지). 데이터 관리에 사진 blob 합 vs 기록 JSON 바이트 + 브라우저 estimate 표시. 원본 별도 보관이라 전체 증가는 10%대.',
  },
  {
    seq: 15,
    date: '2026-07-23',
    topic: '좀비데이터 방지 + 공유 프로젝트 스키마 격리',
    human: '메디컬 앱에서 좀비데이터로 고생했다. 절대 안 생기게. 그리고 Supabase는 메디컬과 한 프로젝트를 쓰되 스키마를 엄격히 분리(한 집 두 방).',
    ai: '좀비 근본원인=병합이 벽시계(updatedAt) 우선이라 시계 스큐로 오래된 활성 사본이 tombstone을 덮음. version 기반 tombstone 우위(진짜 복원만 부활, 동률은 삭제 승)로 전환 제안. 스키마 격리는 이미 ADR-0020(journey)로 존재 — 방=Postgres 스키마, 벽=클라이언트 스키마 고정+소유자 RLS+앱별 버킷.',
    decision: 'mergeDecision을 version 우위로 강화(적대적 유닛). SYNC_PROTOCOL·client에 계약 명문화. 공유 프로젝트+스키마/버킷 격리 채택(메디컬=별도 스키마·버킷, 인증만 공유·RLS로 분리). 서버측 tombstone 강제는 Supabase 연결 시 후속.',
  },
  {
    seq: 16,
    date: '2026-07-23',
    topic: '서버측 좀비 방지 적용 + 프로젝트 실측',
    human: '진행하자(Supabase 연결·동기화). (확인) Travel&Accounting 유지 + 서버측 좀비 방지 지금 적용.',
    ai: '실측: Bugeon 조직에 Medical/Travel&Accounting 두 프로젝트. 여행 앱은 이미 Travel&Accounting의 journey 스키마(회계=public와 한 집 두 방), 메디컬은 별개 집. 서버 트리거로 tombstone 부활 차단 제안.',
    decision: 'journey.trips·moments에 prevent_zombie_resurrection BEFORE UPDATE 트리거 적용(search_path 고정). BEGIN..ROLLBACK로 비공허 검증(프로덕션 무변경). 여행=Travel&Accounting 유지, 메디컬 별개 프로젝트로 격리 확정. 다음: place_lat/lng·media·expense 동기화.',
  },
  {
    seq: 17,
    date: '2026-07-23',
    topic: '다기기 서버 스키마(사진·비용·좌표) + 정정',
    human: '정정: seq15의 "메디컬과 한 프로젝트"는 착오였고 실제로는 회계장부 앱과 한 프로젝트다(여행+회계=Travel&Accounting, 메디컬은 별개). 추천대로 진행.',
    ai: 'journey에 media(+journey-media Storage 버킷)·expenses 테이블과 moments place_lat/lng 추가 제안. 모두 소유자 RLS·초대제·복합 FK(H-02)·tombstone·좀비 트리거로 보호.',
    decision: '마이그레이션 0005~0008 적용(프로젝트 Travel&Accounting). RLS 격리·H-02·좀비 방지 공격검사 트랜잭션 테스트 통과(MEDIA_EXPENSE_RLS_ZOMBIE_PASS), 어드바이저 신규 이슈 0, 프로덕션 무변경. 앱측 동기화 코드+OAuth 실연동은 실기기 검증 필요라 다음 단계.',
  },
  {
    seq: 18,
    date: '2026-07-23',
    topic: '혼선의 기계적 방지 + 실연동 정정',
    human: '진행하자(사진·비용 동기화). 그리고 이런 혼란·혼선을 기계적으로 막는 법은? (그리고 구글 로그인은 이미 끝나지 않았나?)',
    ai: '실측 정정: Google OAuth·여행/순간 동기화는 이미 라이브(HANDOFF "실연동 대기"는 stale). 혼선 2종=①클라↔서버 스키마 드리프트 ②문서↔현실 드리프트. ①은 CI 게이트로 잠글 수 있다고 제안.',
    decision: 'check-schema-parity 게이트 신설(rowmap 필드 ⊆ 서버 마이그레이션 컬럼, 비공허, harness 등록). HANDOFF 실연동 정정. 교훈을 LESSONS §6에 기록(라이브 사실은 파생/실측). sync 코드는 최고위험 표면이라 몰아 짜지 않고 다음 턴에 집중(비용 cascade·큐 전파·Storage 정합).',
  },
  {
    seq: 19,
    date: '2026-07-23',
    topic: '비용 다기기 동기화 구현',
    human: '비용부터 진행하자.',
    ai: 'moments 대칭으로 expense rowmap·서비스 큐 op·sync push/pull 구현. 핵심 위험=순간 삭제/복원 cascade가 비용 tombstone/복원 시 큐 op를 전파해야 함. category/note는 서버 컬럼 추가(무손실).',
    decision: 'domain/expense/rowmap + expenses 서비스 enqueue(create/update/delete) + moments cascade 비용 op 전파 + sync.ts ExpensesRemote·pushPendingExpenses·pullExpenses·runSync 순서(여행→순간→비용). 마이그 0009(category/note). 검증: 스키마 게이트가 rowmap↔서버 정합 확인(0009 아티팩트 누락을 RED로 잡아 보강), rowmap 유닛 왕복, 서버 트랜잭션 round-trip(EXPENSE_SYNC_ROUNDTRIP_OK·좀비 차단, 프로덕션 무변경). 네트워크 실사용은 실기기(trips/moments와 동일 플러밍이라 라이브 확인됨).',
  },
  {
    seq: 20,
    date: '2026-07-23',
    topic: '사진 다기기 동기화 구현',
    human: '사진 진행.',
    ai: '표시본만 Storage 업로드(원본은 로컬 유지·절약 모드), GPS는 PII라 미동기화. 안전 불변식: pull은 로컬 blob 비파괴(다운로드 성공 시만 교체·tombstone은 표시만·다운로드 실패 시 로컬 유지), push는 추가전용.',
    decision: 'domain/media/rowmap(메타만·MediaMeta) + mediaStoragePath + media 서비스 5개 mutation·moments cascade에 media op enqueue + sync.ts MediaRemote(메타+Storage)·pushPendingMedia·pullMedia·runSync(여행→순간→사진·비용). 검증: 스키마 게이트(MediaRow 15↔journey.media), 유닛 4(경로·GPS/blob 미포함·메타 왕복·tombstone), 서버 메타 round-trip(MEDIA_META_ROUNDTRIP_OK·좀비 차단·프로덕션 무변경). Storage blob 업/다운은 샌드박스 미검증 → 실기기 몫(안전 불변식으로 기억 유실은 구조적 불가).',
  },
  {
    seq: 21,
    date: '2026-07-24',
    topic: '비상 복구 체계 — 백업 완전성 게이트 + 절차서',
    human: '메디컬 앱처럼 비상 상황 대응 시스템이 우리 앱에도 갖춰져 있나? 바로 만들자. (그리고 우리 압축 사진은 Supabase에 업로드되나?)',
    ai: '실측 답: 표시본은 Storage(journey-media)에 업로드되고 원본·GPS는 로컬에만 유지(절약 모드·§0). 우리 복구 자세는 오히려 더 튼튼 — 원본은 외부 호스트 의존이 없고(약한 고리 없음), 백업 JSON은 사진을 base64로 품어 자족적, Supabase는 포트로 격리된 교체 가능 부품. 갭 3종=①백업 완전성 게이트 부재 ②복구 절차서 부재 ③연구노트 TSA 부재. ①을 CI 게이트로 잠그자고 제안.',
    decision: 'check-backup-coverage 게이트 신설 — db.ts 테이블 선언(진실원)의 모든 사용자 데이터 테이블이 exportBackup·importBackup 양쪽에서 참조되는지 저장소만으로 대조(syncQueue만 명시 제외), 비공허 자체검사 내장(실파일 뮤테이션으로 RED 확인), harness 8게이트 등록. docs/DISASTER_RECOVERY.md 신설(3계층·시나리오 A~D·기계적 보증·정직한 갭). TSA는 외부 시각 증명이라 별도 논의로 유보(과장 금지).',
  },
  {
    seq: 22,
    date: '2026-07-24',
    topic: '여행별 폴더 백업(ZIP)',
    human: '백업 시 여행별로 폴더로 구분해서 백업하게 할 수 있나? (선택: 여행별 폴더 ZIP + 원본 포함)',
    ai: '브라우저는 일반 다운로드로 실제 OS 폴더를 못 만든다(폴더쓰기 API는 크롬 전용·iOS 불가) → 이식성 있는 정답은 ZIP 안 하위폴더. 사진을 base64 대신 실제 이미지 파일로 풀면 탐색기에서 바로 보기·개별 복원 가능. 라이브러리 없이 바닐라 store-ZIP으로 구현 제안. 기존 단일 JSON은 유지(가장 안전한 통짜 복원본).',
    decision: 'services/zip.ts(무압축 store ZIP 리더/라이터+CRC32, 의존성 0) + backup.ts를 공통 코어(exportCollectRows/importMergeRows)로 리팩터해 JSON·ZIP 두 형식이 같은 수집·병합을 공유. exportBackupZip(여행폴더+trip.json+photos/ 실제파일, 원본 포함, 고아는 _orphans/로 유실 방지)·importBackupZip·importBackupAuto(매직바이트 감지). check-backup-coverage 게이트를 역할기반(export-role/import-role 함수 전 테이블 참조 강제)으로 강화 — 형식이 늘어도 완전성 보증, 비공허(collector에서 localMedia 제거 시 RED). 검증: zip 유닛 5(CRC 벡터·왕복·한글폴더·50엔트리·손상), 표준 unzip -t "No errors"(외부도구 상호운용·CRC 무결성), harness 8게이트·build 그린. 데이터 안전 불변식(병합·빈가드·tombstone) 그대로.',
  },
  {
    seq: 23,
    date: '2026-07-24',
    topic: '비상 복구 강화 — DR 감사관 도입 + 실질 갭 3종 보완',
    human: '외부 disaster-recovery-guardian 서브에이전트를 우리 앱에 적용 가능? (선택: 설치 + 진짜 갭 최대한 모두 보완)',
    ai: '앱-비종속 읽기전용 감사관 — 우리 팀에 그대로 설치 가능(우리 "정직한 완료 §4"와 같은 결). 8기준 대조 결과 지금은 HOLD: ②③(무장된 스케줄·신선도)는 로컬퍼스트·비공개 개인앱이라 "백업 주인=사용자"로 일부러 자동화 안 함(설계상 경계, 이미 문서화). 진짜 갭은 3개 — G1 복원 왕복 드릴 부재, G2 백업 평문, G3 Storage 고아 스윕 부재.',
    decision: 'disaster-recovery-guardian를 .claude/agents/에 verbatim 설치(앱-비종속 유지). G1: backup.ts를 db층(exportCollectRows/importMergeRows)과 순수 직렬화층(serialize/deserialize Json·Zip, FileReader 제거→Node/브라우저 공통)으로 분리 → tests/unit/backupRoundtrip로 export→import 왕복 파리티 드릴(사진 바이트·tombstone·고아·좌표·원본 폴백, 비공허 포함). G2: services/backupCrypto.ts(WebCrypto AES-GCM-256 + PBKDF2 210k, MAGIC 봉투 자동감지, 의존성 0) — 백업 시 선택적 암호구절, dataManager에 암호 입력·복원 needsPassphrase 흐름, 분실 경고. 키 미저장. G3: MediaRemote.remove + pushPendingMedia가 tombstone 반영 후 표시본 Storage 객체 정리(최선노력·유실 위험 0), 마이그 0010(journey_media_delete_own 소유자 폴더격리+초대제 DELETE 정책, DEL-CONTRACT 이행). 검증: 유닛 backupRoundtrip 7·crypto 3, harness 8게이트·build 그린; Storage DELETE 정책 qual이 select/insert/update와 동일 소유자범위 확인, 격리 술어(owner=true·other=false) BEGIN..ROLLBACK, 어드바이저 신규 0(기존 3건만)·프로덕션 무변경. 정직: ②③ 자동 스케줄·오프사이트는 비공개 기본(§3)이라 설계상 사용자 책임 — DR 문서에 경계 명시 유지. 실기기 Storage 실삭제·대용량 암호화 체감은 사용자 몫(로직·정책은 검증됨).',
  },
  {
    seq: 24,
    date: '2026-07-24',
    topic: 'DR 감사관 실행 + 교정 3종 반영',
    human: '설치한 감사관을 실제로 돌려 판정을 받아보자. (그리고 감사관이 권한 교정을 최대한 모두 구현)',
    ai: '감사관(서브에이전트)이 게이트·드릴을 직접 실행하고 HOLD 판정: DR 구조는 강하고 과장 없이 정직하나, 최후 방어선(사용자 백업)이 설계상 사용자 주도라 실제 존재/신선도를 저장소로 검증 불가(소유자 확인 필요)+평문 기본값이 실질 교정. 권고 3: #1 마지막 백업 시각 관측화, #2 평문 PII 내보내기 명시 확인, #3 실기기(fake-indexeddb) 복원 드릴.',
    decision: '감사관 판정 HOLD를 정직히 수용(②③는 로컬퍼스트·비공개 설계 경계). 교정 전부 반영: #1 services/backupMeta.ts(localStorage 마지막 백업 시각·신선도, 캐시성 메타) + 데이터 관리에 "마지막 백업: N일 전"·오래됨/없음 권고 표시(내보내기 성공 시 기록). #2 암호 없이 내보낼 때 window.confirm으로 "암호화 안 됨(사진·GPS·메모 평문)" 명시 확인(암호 있으면 생략). #3 fake-indexeddb dev 의존 + tests/unit/restoreDrill로 importMergeRows를 실 Dexie로 구움(빈db 저장·되읽기·blob 바이트 왕복·빈가드·LWW·tombstone 우위) — 순수층뿐 아니라 db 접근층까지 검증. + backupMeta 유닛(신선도, now 주입). 검증: harness 8게이트·build 그린, 유닛 restoreDrill 4·backupMeta 2·backupRoundtrip 7·crypto 3·zip 5. 남은 HOLD 근거(실제 백업 존재·신선도)는 정의상 앱 밖 사실이라 소유자 확인 몫 — 앱은 관측화·경고·완전성까지 책임(정직한 경계 유지).',
  },
  {
    seq: 25,
    date: '2026-07-24',
    topic: '기울기 보정 요청 → 원근 펴기(4점) 구현',
    human: '기울기 보정 기능도 추가할 수 있나? (키오스크 화면을 비스듬히 찍은 사진 제시. 선택: 원근 보정 추가 + 수평 슬라이더 개선 둘 다)',
    ai: '실측: 수평(기울기) 슬라이더는 v0.24부터 이미 존재(발견성 문제). 제시된 사진의 진짜 문제는 회전이 아니라 원근 왜곡(사각 화면이 사다리꼴) — 문서 스캐너식 4점 펴기(호모그래피)가 필요. 2D 캔버스는 사영변환 미지원이라 역매핑+bilinear를 순수 픽셀 함수로 직접 구현 제안. 편집기 좌표계 계약(잡티·크롭)과 맞물리는 위험 표면이라 헌장 로드 후 신중 진행.',
    decision: 'editor-core: EditState.quad(TL·TR·BR·BL 0..1, 순수 JSON) + squareToQuadCoeffs(Heckbert 단위정사각형→quad 사영) + quadOutputDims(마주보는 변 평균=스캐너 관례) + rotateQuad90/flipQuadH(freeCrop·heals와 동일 규율). pixelops.warpPerspective(역매핑+bilinear, 출력 크기만 루프·경계 클램프, 순수). bake 1.5단계 워프 — 기하 공간을 gd(펴기 후)로 정의해 창·heal 재투영 일관(rd→gd 치환). UI: 📐 펴기 모드(4점 독립 핸들+SVG 사다리꼴, 드래프트는 적용 시 undo 한 단계), 회전/반전 시 quad 동반 변환, 수평 라벨 "수평(기울기)"·±15°. 검증: 유닛 10(호모그래피 모서리 정확 매핑·워프 항등/절반 추출·비공허 기울임·quad 회전 4회 원위치·isIdentity), 라이브 33/33 PASS(4점 표시→핸들 드래그→적용 픽셀 실변화→undo 원복, 콘솔 에러 0), harness 8게이트·build 그린. 헌장 §1-4 좌표계 계약에 quad 명문화. 실기기 터치 드래그 체감은 사용자 확인 권장.',
  },
  {
    seq: 26,
    date: '2026-07-24',
    topic: '전체보기 뷰어 확대/이동(반응형) + 백업 파일명 규칙',
    human: '1) 전체보기를 접속 기기에 맞게 최적화(반응형)? 2) 백업 파일명을 "날짜_시간_제목_용도"로? (선택: 둘 다 추천안)',
    ai: '뷰어는 contain이라 넓은 화면에서 세로 사진 좌우 여백이 큼 — 세로 사진은 비율상 꽉 채우면 잘라야 하니 실질 최적화는 확대. 파일명은 trip.json 메타 경로로 복원하므로 파일명 자유 변경해도 복원 안전(같은 분·제목 충돌은 id8 접미로 방지).',
    decision: '① 뷰어: 확대/이동 추가 — scale/tx/ty + zoomAround(화면점 고정 확대: 휠·핀치·더블탭 공통) + clampPan(화면 밖 이탈 방지), 포인터 통합(1개=확대 전 스와이프/확대 중 팬, 2개=핀치), show() 시 리셋, 방향키/0 키 리셋, 반응형 CSS(폰 여백 최소·태블릿 24px·100dvh·safe-area·is-zoomed 커서). ② 파일명: services/backup에 stampFromISO·photoFileBase(날짜_시간_제목__id8, FS안전 fsSafe 추출) + PURPOSE(원본/표시본/썸네일) → serializeZip이 사진을 "20260717_0617_제목_원본__id8.jpg"로(제목=순간 제목→여행 제목→사진), 최상위 백업명 bugeon-journey_YYYYMMDD_HHMM.{zip,json}. 검증: 유닛 backupNaming 5(형식·FS금지문자·충돌방지)·backupRoundtrip 7(파일명 바뀌어도 메타 경로로 복원 성공=안전 증명), verify-editor-live 35/35(뷰어 휠 확대 2.05x·0키 원복·무회귀), harness 8게이트·build 그린. 실기기 핀치/더블탭 체감은 사용자 확인 권장.',
  },
  {
    seq: 27,
    date: '2026-07-24',
    topic: '가로 태블릿 전체보기 잘림 수정',
    human: '태블릿에서 전체사진으로 볼 수가 없어요(가로 사진 위아래 잘림). 참고로 모바일 확대화면은 해결됨.',
    ai: '근본형: v0.40에서 뷰어를 display:grid; place-items:center로 바꾸며 img{max-height:100%}가 auto-sized grid 트랙에 대해 해석 안 돼 높이 제약 실패 → 가로 화면(높이 기준)에서 폭만 맞고 세로 오버플로(세로 화면은 폭 기준이라 안 드러남 — 사용자의 "모바일은 정상"이 이를 확증). + height:100dvh가 inset:0과 과잉제약. flex 중앙정렬 + object-fit:contain 제안.',
    decision: '.photo-viewer를 flex 중앙정렬(definite-height 컨테이너에서 max-height:100% 신뢰)로 전환 + img object-fit:contain 안전망 + height:100dvh 제거. 검증(현실로): verify-editor-live에 가로 뷰포트(1600×1000) 측정 테스트 추가 — 비공허 확인(옛 grid로 되돌리면 1552×1164 오버플로 FAIL, 수정본 1269×952 PASS). 37/37 PASS·harness 8게이트·build 그린. 교훈(스킬 §4 등재): 반응형 회귀는 세로/가로 두 방향 모두 측정해야 잡힌다 — 세로 뷰포트만 보면 높이-제약 결함을 놓친다.',
  },
  {
    seq: 28,
    date: '2026-07-24',
    topic: '가벼운 백업(원본 제외) 옵션',
    human: '여행폴더 백업에 원본 뺀, supabase에 저장된 것만 받는 옵션을 넣으면? 완벽한 전체백업은 json으로 진행 맞죠? (선택: 체크박스 토글)',
    ai: '확인: JSON은 원본 포함 완전백업 맞음(현재 ZIP도 원본 포함이라 둘 다 완전백업 상태). Supabase Storage엔 표시본만 올라감(원본·GPS 미동기화) → "원본 제외"=표시본+썸네일+메타(클라우드와 사실상 동일·브라우징 가능·약 1/8 용량). 메커니즘은 이미 존재(exportBackupZip(includeOriginals=false)·왕복 테스트 통과) — 버튼 대신 체크박스 토글 추천(카면 방지·JSON=완전백업 유지).',
    decision: 'dataManager 백업 패널에 "원본 사진 포함" 체크박스(기본 켬) 추가 — ZIP 버튼이 checkbox.checked를 exportBackupZip에 전달, 해제 시 파일명 접미 "_표시본만". 안내문·주의문을 완전백업(원본 포함)=JSON 중심으로 정정. 검증: backupRoundtrip에 가벼운 백업 단언 강화(light<full 크기·_원본 엔트리 없음·표시본 폴백 복원), harness 8게이트·build 그린. 체크박스는 이미 검증된 boolean 파라미터 토글이라 자동층으로 충분(실기기 다운로드 UX는 사용자 확인). 데이터 안전 불변식 그대로 — 원본은 로컬·완전백업에만, 가벼운 백업 복원은 표시본 폴백(기억 유실 아님).',
  },
  {
    seq: 29,
    date: '2026-07-24',
    topic: '여행 목록에서 바로 삭제(발견성)',
    human: '여행 목록에 삭제 기능이 없네요. 추가하는게 어떨까요?',
    ai: '실측: 여행 삭제 서비스·안전장치(cascade tombstone·실행취소·휴지통)는 Phase 3c부터 존재하나 상세→편집 패널 안에만 노출돼 발견성이 낮음. 목록 카드에 삭제 버튼을 얹되 기존 안전장치를 그대로 재사용 제안(복구 가능성 우선).',
    decision: 'home.ts tripCard를 button→div(role=button)로 전환(버튼 중첩 회피, archivedCard 패턴)해 🗑 삭제 버튼 중첩(stopPropagation). deleteTrip(t): window.confirm(순간·사진 함께 삭제·복구 가능 안내) → softDeleteTripLocalFirst → refresh → showUndoToast(restoreTripLocalFirst). 서버 전파는 trySync. CSS .trip-delete(우상단 원형·danger hover). 검증: verify-editor-live에 목록 삭제 테스트 추가 — 확인 수락 시 카드 제거(1→0), 실행취소로 복원(0→1), 39/39 PASS·콘솔 에러 0, harness 8게이트·build 그린. 하드삭제 없음(§0)·복구 가능(§5) 그대로.',
  },
  {
    seq: 30,
    date: '2026-07-24',
    topic: '설계 개요도(배선맵) — 데이터가 화면까지 닿는 큰 그림',
    human: '메디컬 앱의 설계 개요도처럼 이미지·프레임 동일하게. 클릭하면 로딩되게. 발전원부터 말단까지 배선도 기계적으로 도식. (선택: 개발자 정보 안 · 완전 범위)',
    ai: '이건 새 기능이 아니라 우리 LESSONS §3(배선맵 "발전원→배선→콘센트", 화면까지 닿아야 100점) + §7(SSOT→생성→게이트)를 화면으로 구현하는 것. 이미 DOMAIN_REGISTRY가 발전원 SSOT. 핵심: 손그림 금지 — 실제 레지스트리+Dexie 실카운트+라우터에서 자동 생성하고 CI 게이트로 그림↔현실 대조해야 끊긴 배선을 눈+게이트로 잡아 오류가 준다(사용자 직관 정확).',
    decision: 'app/blueprint.ts(SSOT: SOURCES 발전원 9(실장 4·계획 5)·SHAPING·STORAGE·SCREENS 7·selfCheck 순수·liveCounts Dexie) + ui/screens/designOverview.ts(메디컬 프레임 동일: 자가점검 점수+막대+그룹, ①태어남 실카운트 ②다듬기 ③보관·동기화 ④화면 연결됨/정보 배지, 범례). 개발자 정보(aboutApp)에 진입 버튼. scripts/check-blueprint.mjs(9번째 게이트): db.ts 사용자 테이블⊆implemented SOURCE·hasRowmap→rowmap 파일·hasSync→sync.ts 참조·SCREEN.file 실재 대조, 비공허(빠진 발전원 RED). 검증: 유닛 blueprint 4(점수100·로드맵·화면연결·유령배선 금지), 게이트 비공허(localTrips 매핑 제거 시 RED), verify-editor-live 42/42(개발자정보→설계개요도→4단계·점수100·실카운트 여행=1 자동 채움·콘솔0), 스크린샷으로 프레임 일치 사용자 확인. harness 9게이트·build 그린. 정직: 계획 도메인은 "예정"으로 표시(감점 아님). LESSONS §3 배선맵 생성기 후속과제 해소.',
  },
  {
    seq: 31,
    date: '2026-07-24',
    topic: '손그림 조사 → 카운트/게이트 목록 기계화(자동 집계 + 게이트)',
    human: '손으로 그리는 것들 모두 조사해서 기계화 가능하면 모두 기계화. 특수한 경우면 물어봐. (메디컬 앱 "기계화 검증 흐름도" 이미지 참조)',
    ai: '조사 결과 실측 드리프트 발견 — 가이드 화면이 "6게이트·26에이전트·유닛60"을 손 스냅샷으로 적어 실제(게이트 10·에이전트 28)와 어긋남(guide.ts가 스스로 "파생 게이트는 후속" 인정). LESSONS §7(SSOT→생성→게이트) 대상. 생성 파일 + 커밋본==재생성본 게이트로 제안.',
    decision: 'scripts/gen-registry.mjs → src/app/registry.gen.ts(GENERATED: gates 목록·gateCount·agentCount·screenCount·migrationCount·changelogCount·researchCount를 harness.mjs·.claude/agents/·화면·마이그·changelog·researchLog에서 자동 집계). scripts/check-registry-gen.mjs(10번째 게이트): 커밋본==재생성본 대조(비공허 자체검사, 손상 시 RED 재현 확인). guide.ts가 REGISTRY에서 게이트 목록·개수를 파생(손 나열 제거, GATE_DESC만 설명). tests/unit/logIntegrity(6): changelog 0.01 연속·날짜 내림, researchLog seq 1..N 연속·날짜 오름·human/ai/decision 채움. 문서 프로즈 하드카운트(HANDOFF·CLAUDE.md "9게이트·26에이전트")는 숫자를 빼고 registry.gen 참조로 교체(드리프트 원천 제거). 검증: harness 10게이트·build·verify-editor-live 42/42 그린. 특수 케이스는 사용자에게 질문(전용 대시보드 화면·남은 프로즈 카운트 게이트).',
  },
  {
    seq: 32,
    date: '2026-07-24',
    topic: '기계화 검증 흐름도 대시보드 + 문서 프로즈 카운트 게이트',
    human: 'seq31의 두 특수 케이스 답: (1) 게이트를 카테고리별로 보여주는 "기계화 검증 흐름도" 대시보드 화면을 만들자. (2) 문서 산문 속 숫자에 전용 게이트를 추가하자.',
    ai: '두 손그림 잔여를 마저 기계화. (1) 대시보드는 REGISTRY.gates에서 파생(손 나열 금지)해 정적·자동생성·유닛 카테고리로 묶어 표시. (2) 문서 프로즈 카운트는 seq31에서 "숫자 제거"로 임시 처리했으나, 숫자를 다시 넣고 싶을 때를 위해 마커+게이트로 원천 봉쇄 — <!--reg:키-->값<!--/reg--> 마커를 gen-registry가 자동으로 심고 check-doc-counts가 대조.',
    decision: 'app/gates.ts(공유 GATE_DESC·GATE_CATEGORY·CATEGORY_LABEL — guide/mechChecks 두 화면이 설명을 손으로 중복 안 쓰게). ui/screens/mechChecks.ts(openMechChecks: 4단계 흐름 + 게이트 개수 배지(REGISTRY.gateCount) + 카테고리별 게이트 카드(REGISTRY.gates.filter(categoryOf) 파생) + 라이브 렌더 별도 섹션). aboutApp·guide에 진입 버튼. gen-registry.mjs에 findMarkers/patchMarkers(순수) + DOC_FILES 추가, 실행 시 문서 마커 자동 재심음. scripts/check-doc-counts.mjs(11번째 게이트): DOC_FILES의 <!--reg:키-->값<!--/reg-->이 실제 registry와 일치하는지 대조, 알 수 없는 KEY도 RED, 비공허 자체검사(맞는 값 통과·틀린 값·오타 KEY RED). HANDOFF에 게이트 개수 마커 시연 삽입. 검증(현실로): harness 11게이트 PASS, 문서 마커 99로 손상 시 RED·복원 시 PASS 재현, verify-editor-live 45/45(기계화 흐름도 4단계·배지 자동집계·카드=게이트+라이브 1·콘솔0), build 그린. registry.gen gateCount 10→11·screenCount 8→9 자동 반영. **결함군 승격(자기적용)**: 게이트를 설명하는 프로즈가 게이트가 찾는 마커 문법과 충돌 — Phase 7b 기록에 예시로 적은 <!--reg:KEY-->가 실제 마커로 오인돼 스스로 RED(게이트 비공허 실증). 근본형: "검사 대상의 문법을 문서가 리터럴로 포함하면 오탐". 처방: KEY 정규식을 [A-Za-z0-9_]로 좁혀, 문서 예시는 한글 KEY(키)로 적으면 매칭에서 제외 — 실제 마커(영문 KEY)만 검사.',
  },
  {
    seq: 33,
    date: '2026-07-24',
    topic: '통화 UZS(우즈베크 soʻm) — VND 교체 + 달러 다음 배치',
    human: 'VND 대신 우즈벡 화폐단위 UZS로 바꾸자. 위치도 달러 다음으로 배치(스크린샷: 통화 드롭다운).',
    ai: '사용자는 타슈켄트 소재(우즈베키스탄)라 실사용 통화가 UZS. VND는 format.ts CURRENCIES에만 존재(도메인 단일 출처). 솜은 접두 심볼이 없고 관례상 금액 뒤 "soʻm" — 접두로 위조하면 어색·부정확(§정직: 심볼 위조 안 함). 최소·원칙적 개선으로 suffix 지원 추가 제안.',
    decision: 'domain/expense/format.ts: CurrencyMeta에 optional suffix 추가, CURRENCIES에서 VND 제거하고 { UZS, soʻm, decimals 0, suffix true }를 USD 바로 뒤에 삽입(KRW·USD·UZS·JPY·EUR). formatMoney는 suffix면 "num symbol", 아니면 "symbol num". 드롭다운(tripDetail.currencySelect)은 CURRENCIES를 그대로 순회하므로 순서·라벨 자동 반영(SSOT 파생). 테스트 잠금: expenseFormat "UZS→1,000,000 soʻm(뒤) / JPY→¥500(앞)". 데이터 안전: 기존 VND 비용이 있으면 알 수 없는 통화 폴백으로 "금액 VND"로 정직 표시(원금액·코드 보존·유실 0·§1). 검증: typecheck·유닛 9/9·harness 11게이트·build 그린.',
  },
  {
    seq: 34,
    date: '2026-07-24',
    topic: '통화 목록 확장 — 세계 36개 통화(네이티브 드롭다운)',
    human: '"드롭다운 방식으로 가죠." (통화 선택 관련) → 명확화 질문에 "통화 목록 확장" 선택.',
    ai: '통화 선택은 이미 네이티브 select. "확장"=더 많은 세계 통화. 커스텀 검색 콤보박스는 접근성·모바일 위험·무게 증가 → 네이티브 select는 이미 타입어헤드(코드 첫 글자 입력 시 이동) 제공하므로 목록만 늘리면 검색성도 확보(10초 기록 흐름·모바일 OS 피커 유지). 심볼 없는 통화를 위조하지 않도록 포맷 계층 보강 필요.',
    decision: 'domain/expense/format.ts: CURRENCIES를 5→36(자주 쓰는 KRW·USD·UZS·JPY·EUR 상단 유지 + 세계 통화 코드 알파벳순). CurrencyMeta.symbol 빈 문자열 허용 → formatMoney가 심볼 없으면 "num code"(정직, decimals는 유지), 있으면 suffix/prefix. 관례 반영: 북유럽 kr·PLN zł·CZK Kč·UZS soʻm·VND ₫는 suffix. tripDetail.currencySelect 라벨은 symbol 있으면 "symbol code", 없으면 code만(빈 심볼 중복 방지). DB 영향 0(originalCurrency 자유 문자열). 테스트 잠금(12): £ 앞·AED/CHF 코드 뒤·NOK/SEK/PLN suffix·XXX 폴백·코드 유일성·상단 5개 순서. 검증: typecheck·유닛 12/12·harness 11게이트·build·verify-editor-live 45/45 그린. 정직: 여러 통화가 $·¥·kr 심볼을 공유하나 드롭다운은 코드로 구분·포맷은 심볼 그대로(위조 아님).',
  },
  {
    seq: 35,
    date: '2026-07-25',
    topic: '환율 자동 환산(사용일 기준) — 제공자 선택을 실측 제약 속에서',
    human: '환율 자동계산 추가(외화↔원화, 비용 사용일 환율 기준). 무료 조회 가능한 걸로. 더 좋은 방안 있으면 변경 가능. 목적은 사용자 편의. (참고자료: Frankfurter 권장·Fawaz 보조)',
    ai: '참고자료의 "Frankfurter가 UZS 지원" 주장을 검증하려 했으나 **샌드박스 네트워크 정책이 api.frankfurter.dev·cdn.jsdelivr.net을 모두 차단**(curl 403·WebFetch 403)해 실측 불가. 훈련 지식 기준으로 Frankfurter는 ECB 기준환율 기반이라 지원 통화가 ~30개고 **UZS는 없을 가능성이 크다**(ECB가 솜을 고시하지 않음) — 사용자가 우즈베키스탄 거주라 UZS는 필수 조건. 그래서 참고자료의 우선순위를 뒤집어 Fawaz(200+ 통화·UZS 포함·날짜 고정 URL로 과거 환율·CC0·무제한)를 주 제공자로, Frankfurter를 보조로 제안. 미검증 사실이므로 어댑터 분리 + 실패 시 무해 degrade + 순수 계산 픽스처 검증으로 설계.',
    decision: 'domain/expense/fx.ts(순수): FxRateTable(date·base·rates·source·fetchedAt) · rateOf(기준통화=1·없으면 null) · convertAmount(**표 하나로 양방향** — from→base→to) · isFxFresh(**과거 날짜는 영구 유효**, 오늘만 TTL 6h) · fxDateFor(미래는 오늘로 당김) · convertTotals(환산 못 한 통화를 skipped로 노출). services/fx.ts: 제공자 2단(fawaz jsDelivr→pages.dev 예비, frankfurter) + Dexie v5 localFxRates 캐시 + 전부 실패 시 오래된 캐시 반환·예외 없음. UI: 비용 칩에 "≈ 환산값"을 .chip-approx(옅게·구분선)로 덧붙이고 title에 날짜·출처 표기, 여행 통계에 "환산 합계"(각 비용을 **자기 사용일** 환율로 환산·못 한 통화는 라벨에 명시), 데이터 관리에 기준통화 카드. **원금액 불변(H-04)**: 사용자 입력을 절대 덮지 않고 파생 표시만 추가(원칙 #2). 게이트 의무 이행: CSP 3호스트를 index.html+check-csp REQUIRED에 **같은 커밋**으로 추가(ADR-0023 규율), localFxRates를 check-backup-coverage·check-blueprint EXCLUDE에 근거 주석과 함께 등록(파생·재취득 가능=기억 아님). **게이트 비공허 실증**: 새 테이블 추가 시 두 게이트가 실제로 RED를 냈고(백업 누락·끊긴 발전원) 분류 후 통과. 검증: 유닛 fx 20/20(양방향·왕복·null 정직·TTL·미래날짜·skipped), harness 11게이트, verify-editor-live **48/48**(환율 설정 렌더·기본 KRW·선택 read-back·**콘솔 에러 0**=네트워크 차단 환경에서도 무해 degrade 실증), build 그린. 정직한 미검증: 실제 환율 응답·UZS 지원 여부는 실기기 확인 몫.',
  },
  {
    seq: 36,
    date: '2026-07-25',
    topic: '환율 배지 탭 → 적용 환율일·기준환율 상세(검산 가능하게)',
    human: '환율 배지를 클릭하면 적용환율일과 기준환율을 볼 수 있게 구현하면 좋을 거 같은데. (직전 확인: 실기기에서 50,000 so\u02bbm ≈ ₩6,165 — UZS 조회·과거일 적용 실증)',
    ai: 'v0.49는 근거를 title 속성(툴팁)에만 담았는데 **모바일에선 title이 사실상 보이지 않는다** — 사용자가 안드로이드에서 쓰므로 실질적으로 접근 불가였다. 게다가 "숫자를 그냥 믿으라"는 UI는 정직한 완료 규율과 어긋난다. 탭하면 펼쳐지는 실제 패널로 승격하고, 사용자가 계산기로 검산할 수 있게 단위환율·계산식까지 노출 제안.',
    decision: 'domain/expense/fx.ts에 순수 함수 2개 추가: unitRate(1 from = ? to — 양방향 역수) · formatRate(통화 소수자릿수를 쓰면 0.1087이 "₩0"으로 뭉개지므로 별도 규칙 — 1 미만은 유효숫자 4자리). tripDetail: .chip-approx를 span→button(aria-expanded·aria-label)으로 승격, 탭하면 카드 하단에 .fx-detail 패널 표시(같은 배지 재탭=접힘, 다른 배지=교체). 패널 내용 — **적용 환율일**(요청일과 다르면 "사용일 ○○은 고시 없음 → 직전 고시일"로 이유 명시) · **단위환율 양방향** · **계산식**(원금액 × 단위환율 = 환산값) · **출처** · 기준환율 주의 문구. 검증: 유닛 fx 26/26(단위환율 역수 관계·formatRate 경계·환산값↔단위환율 일치=검산 가능성 증명), **verify-editor-live 57/57** — 샌드박스가 환율 API를 차단하므로 **Dexie localFxRates에 픽스처를 직접 주입**해 UI 경로만 검증(네트워크 검증 아님을 명시): 배지 렌더 ≈₩5,435 · 초기 aria-expanded=false · 탭 후 상세에 적용일·양방향 환율·계산식·출처 표시 · 재탭 접힘 · 콘솔 에러 0. harness 11게이트·build 그린.',
  },
  {
    seq: 37,
    date: '2026-07-25',
    topic: '통화 선택에 국기 — 손 테이블 대신 코드에서 파생',
    human: '화폐단위 앞에 국기가 함께 있음 좋을 거 같아요. (스크린샷: 36개 통화 드롭다운)',
    ai: '국기 36개를 손으로 적는 대신 파생 가능함을 발견: ISO 4217 통화코드의 앞 두 글자가 곧 ISO 3166-1 alpha-2 국가코드다(KRW→KR, UZS→UZ, EUR→EU도 유효한 지역표시자쌍). 지역표시자 코드포인트 산술로 생성하면 손편집 중복이 아예 없고(§7), 새 통화를 추가해도 국기가 자동으로 따라온다. 예외는 ISO 4217의 X.. 초국가 코드(XAF·XDR 등)뿐 — 나라가 없으므로 빈 문자열(위조 금지).',
    decision: 'domain/expense/format.ts: currencyFlag(code)=코드 앞 2글자→지역표시자 이모지(X 접두는 빈 문자열) + currencyLabel(c)=국기·심볼·코드 조합(빈 값 자동 생략). tripDetail.currencySelect와 dataManager 기준통화 선택기가 둘 다 currencyLabel을 쓰도록 통일(라벨 규칙을 두 곳에 손으로 쓰던 중복도 함께 제거). 환산 칩(formatMoney)에는 넣지 않음 — 타임라인은 기억이 주인공이라 국기가 노이즈. 검증: 유닛 16/16(파생 정확성·대소문자·X 접두 빈값·라벨 형식·지원 통화 전부가 국기를 가진다=새 통화 추가 시 자동 회귀 방지), verify-editor-live 59/59(36개 옵션 전부 국기 접두·"🇰🇷 ₩ KRW" 형식·콘솔 0). harness 11게이트·build 그린. 정직: Windows는 국기 이모지를 글자쌍(KR)으로 그리지만 정보는 남으므로 그대로 둔다.',
  },
  {
    seq: 38,
    date: '2026-07-25',
    topic: '타임라인 날짜가 하루 밀림 — UTC 절단 결함군(M-utc-slice)',
    human: '7월 15일 사용금액인데 왜 7월 16일로 적용했어? (스크린샷: 타임라인 헤더 7월 15일 · 시각 06:48 · 적용 환율일 2026-07-16)',
    ai: '실측 결과 환율이 아니라 **타임라인이 틀렸다**. timeline.ts dayKey가 occurredAt.slice(0,10)으로 UTC 날짜를 뽑는데, 시각 표시(timeLabel)·발생 시각 입력(toLocalInputValue)·백업 파일명(stampFromISO)·환율(localDate)은 전부 로컬이다. KST에서 2026-07-15T21:48Z = 로컬 7/16 06:48 → 헤더만 7/15로 밀렸다. 사용자가 입력한 발생 시각도 7/16 06:48이었으므로 환율 7/16이 정답. 앱 전체 날짜 파생 지점을 훑어 UTC를 쓰는 곳이 이 한 곳뿐임을 확인.',
    decision: '결함군 승격(§6): ① 날짜 파생 SSOT를 domain/time.ts localDate로 신설(fx.ts에서 이동·재수출), timeline.ts dayKey가 이를 사용 → "그 날 = 사용자의 로컬 달력 날짜" 계약 명문화. ② **check-timezone 게이트(12번째)** 2층 방어 — (A) 정적: src/에서 ISO 절단(.slice(0,10)) 금지, 날짜 아니면 // not-a-date 예외(주석 오탐 방지 codePart 포함), (B) 동적: 유닛 스위트를 Asia/Seoul·Pacific/Honolulu(동/서 양방향)에서도 재실행. ③ 옛 timeline 테스트가 UTC 전제라 KST에서 깨짐 → 픽스처를 at(y,mo,d,h) 로컬 구성으로 전환(어느 시간대에서도 성립) + 회귀 테스트 2건(로컬 새벽 06:48이 전날로 안 밀림·하루 전체 시각대 훑기). **핵심 교훈**: 우리 CI·샌드박스가 UTC라 이 부류는 유닛으로 구조적으로 안 보인다 — 게이트 (B)가 본 방어선이다. 검증: 비공허 실증(dayKey를 옛 slice로 되돌리면 RED, 복원하면 GREEN), 유닛 182/182이 UTC·KST·하와이 3개 시간대 통과, harness 12게이트·build 그린.',
  },
  {
    seq: 39,
    date: '2026-07-25',
    topic: '넓은 화면 레이아웃 — 780px 기둥 → 2단 배치',
    human: '태블릿 울트라 화면에서는 가운데 몰려 있는걸로 나오네요. 이거 보기좋게 바꿀 수 없을까요? (스크린샷: 2960px 가로, 본문 780px, 양옆 각 350px 공백)',
    ai: '.screen-home/.screen-detail이 max-width 780px 고정이라 넓은 화면에서 양옆이 비었다. 단순히 폭만 늘리면 한 줄이 길어져 읽기 나빠지므로(입력 필드가 1400px로 늘어남) 남는 폭을 **의미 있게** 쓰자고 제안: 상세는 [기록 폼 | 타임라인] 2단, 홈은 카드 3열. 폼을 sticky로 두면 타임라인을 내려봐도 기록이 손 닿는 곳에 남아 "10초 기록" 흐름이 유지된다.',
    decision: 'DOM: 좌측 묶음 .detail-compose 신설(편집패널·폼·안내) — DOM 순서는 기록→타임라인 그대로라 화면읽기·키보드 순서 불변. CSS: @media(min-width:1100px)에서 .detail-body를 grid[minmax(340px,30%) 1fr]로, .detail-compose sticky, .trip-list 3열, max-width 1200px(≥1600px는 1360px 상한 — 한 줄이 지나치게 길어지지 않게). 덤으로 기존 결함 수정: .detail-hero 위쪽 패딩이 절대배치 버튼줄(top16+높이40)을 안 비워둬서 짧은 여행에서 상태 배지가 뒤로가기 버튼과 겹치던 것 → padding-top으로 버튼줄 공간 예약. 검증(현실로): 12개 폭(412~1920, 경계 1099/1100/1101 포함) 실측 — **가로 넘침 전부 0**, 2단 전환이 정확히 1100px에서, 탭 울트라(1480)에서 본문 780→1200px. 스크린샷으로 시각 확인(2단 배치·배지 겹침 해소·홈 3열). verify-editor-live에 영구 회귀 검사 7건 추가(넘침 0·2단·경계 1099 세로 유지·경계 1100 전환·폰 세로·배지 비겹침) → 66/66. harness 12게이트·build 그린.',
  },
  {
    seq: 40,
    date: '2026-07-25',
    topic: '상태 표시의 시각 위계 — 전폭 배너 → 상태별 알약',
    human: '동기화된 여부를 확인하는 건 좋은데 너무 화면을 과하게 사용하는 거 아닐까? 디자인 고려해서 적절하게 바꿀 방법은?',
    ai: '.sync-note가 text-align:center + 블록 <p>라 "동기화됨" 두 단어에 전폭 배너를 썼다. 상태 4종을 뜯어보니 성질이 다르다 — 동기화됨은 **정상(정상 상태)**이라 사실상 노이즈고, 대기/로컬모드/로그인안내는 알아둘 정보, 저장실패는 놓치면 안 되는 것. 균일한 시각 무게가 문제의 뿌리 → "평소엔 조용히, 문제일 땐 눈에 띄게" 위계 제안. 사용자가 "확인하는 건 좋다"고 했으므로 숨기지 않고 줄인다.',
    decision: 'ui/dom.ts에 setNote(node,text,state) 공유 헬퍼 신설 — ok/info/error 3단(두 화면이 같은 규칙을 쓰도록 §7, 규칙을 두 번 쓰지 않는다). CSS: .sync-note를 align-self:flex-start + inline-flex 알약으로(전폭 → 내용 폭), 패딩 10/14→5/11, 폰트 0.85→0.76rem. .is-ok는 배경 없이 opacity .62(거의 안 보이게), .is-info는 sem-sky 12% 알약, .is-error는 sem-pink 15% + 굵게. home(동기화됨=ok·나머지=info)·tripDetail(저장됨=ok·사진 진행=info·저장 실패=error) 배선. 검증(현실로): 세 상태를 나란히 렌더해 시각 비교 스크린샷, ok 상태 실측 **112×28px = 화면폭의 8%**(이전 100%). verify-editor-live에 회귀 검사 추가(전폭 배너 금지: 폭 < 뷰포트 50%) → 67/67. harness 12게이트·build 그린.',
  },
  {
    seq: 41,
    date: '2026-07-25',
    topic: 'R2 이관 설계 개정 — 메디컬 실증 구조 채택 + 앱 내 설정 가이드',
    human: 'Cloudflare R2를 메디컬앱에서 이미 작업했다. 인수인계 문서와 media-sign 함수 소스를 공유하니 우리 앱 설계에 반영해라. 그리고 앱 내에도 설정 가이드를 상세히 기록할 거니 캡처를 공유하면 잘 기록해 두면 좋겠다.',
    ai: '받은 문서는 실측 기록(59분 소요·틀렸던 12지점 포함)이라 신뢰도가 높다. 대조 결과 내 1판 설계(Cloudflare Worker + R2 바인딩)를 폐기하는 게 맞다고 판단 — 실증 구조(Supabase Edge Function presign)가 우리에게 더 낫다: ①1판의 최대 위험이었던 "Worker가 Supabase JWT 서명을 직접 검증"이 통째로 사라진다(Edge Function이 네이티브 처리) ②Cloudflare Worker 배포 자체가 불필요 ③바이트가 함수를 통과하지 않아 크기 제한 없음. 동시에 **내가 1판에 틀리게 적은 사실 발견**: "앱마다 각자 10GB"는 오류이고 무료 한도는 계정 전체 합산이다 → 이관 근거 하나가 약해진다. 그리고 우리 앱에만 있는 충돌 발견: 인수인계 구조는 r2.dev 공개 URL을 쓰는데 이는 URL을 아는 사람이 인증 없이 열람 가능 → 비타협 원칙 #3(개인자료 기본 비공개)과 충돌. 메디컬은 "개인 식별 정보 사진은 안 올린다"로 완화했으나 우리는 개인 사진이 주인공이라 같은 완화가 성립하지 않는다.',
    decision: 'docs/STORAGE_R2_PROPOSAL.md를 개정 2판으로 전면 재작성: 채택 구조를 Edge Function presign으로 교체, §2 격리를 "토큰 스코프가 벽"으로 재정의(공유 함수·프록시 업로드 기각 근거 포함), §6 검증 사다리 4단(앞 단계가 뒤를 보장하지 않음 — CORS는 3번에서만 드러남)을 릴리스 체크리스트로 채택, **§7에 내가 틀렸던 4가지를 표로 명시**(쿼터 합산·Worker 구조·JWT 위험·저장 클래스), **§8을 최대 미결 쟁점으로 격상**(공개 URL vs 원칙 #3 — A 수용/B 읽기도 presign/C 커스텀 도메인, 권고는 B이되 사용자 결정 필요·B는 미실증임을 정직하게 명시). 앱 내 가이드: ui/screens/r2Setup.ts 신설(9단계 카드 + 위험도 3단 경고 9건 + 확보할 값 5개 + 검증 사다리 + 증상→원인 진단표), [데이터 관리 › R2 저장소 설정]에서 진입, STEPS[].shot에 public/setup/r2/ 경로를 지정하면 스크린샷이 함께 뜨는 구조(사용자가 캡처를 주면 채움). public/setup/r2/README.md에 캡처 규칙 명시 — **토큰 발급 결과 화면은 절대 넣지 않는다**(Secret 평문). 검증: harness 12게이트·verify-editor-live 72/72(단계 9·위험 경고 9·버킷 잠금/캡처 금지/검증 사다리 문구 포함)·build 그린. 라이브 테스트 삽입 위치 오류(.data-open은 홈에만 존재)를 실패로 잡아 홈 구간으로 이동 — 게이트가 아니라 라이브가 잡은 사례.',
  },
  {
    seq: 42,
    date: '2026-07-25',
    topic: 'R2 읽기 정책 결정 — 공개 URL을 쓰지 않는다',
    human: '처음부터 초등학생도 이해할 수 있게 설명해 달라. 그리고 네 추천대로 하면 앱에서 삭제·저장은 문제 없나? … B로 가자.',
    ai: '두 질문에 코드로 답했다. 삭제·저장은 읽기 정책과 무관하다(업로드는 어느 쪽이든 서명 PUT, 삭제는 서버측 서명). 그리고 결정적 사실: 우리 앱은 화면에 사진을 URL이 아니라 로컬 blob으로 그린다(tripDetail의 thumbBlob·displayBlob) → 읽기 서명이 필요한 순간은 새 기기가 그 사진을 처음 받을 때 사진당 1회뿐. 메디컬 앱은 URL로 직접 표시하는 구조라 A(공개 URL)가 합리적이었지만, 구조가 다르니 결론도 달라진다 — 우리는 B의 대가를 거의 치르지 않고 원칙 #3을 지킬 수 있다. 다만 앞서 "메디컬 KEY_RE를 우리 경로 형식에 맞추겠다"고 한 계획은 스스로 개선했다: 함수가 검증된 sub로 키를 생성하면 경로 규약이 그대로 유지돼 마이그레이션이 0이면서(원본 경로를 안 건드리는 쪽이 원칙 #1에 안전) "서버가 키를 만든다"는 보안 성질도 지킨다.',
    decision: 'ADR-0024 — 읽기 정책 B 확정(버킷 비공개 + presigned GET, R2_PUBLIC_BASE 미사용·시크릿 4개). supabase/functions/media-sign/index.ts 신설(SigV4 자체 구현, 객체 키를 서버가 생성, verify_jwt에 의존하지 않고 /auth/v1/user로 실제 인증 확인, 삭제는 함수가 서명·실행). src/services/r2.ts 어댑터 + sync.ts는 바이트 3종만 분기(VITE_MEDIA_STORE=r2, 기본값은 기존 경로 → 되돌리기는 환경변수 하나). Deno.serve를 전역 가드로 감싸 Node에서 import 가능하게 만들어 함수 자체를 유닛으로 검사(13개: 경로 파리티·클라이언트 키 위조 무시·미인증 401·서명에 URI/메서드 참여·비밀 미유출), 결함 2종 주입으로 비공허 실증. CSP connect-src에 R2 추가하되 img-src는 열지 않음(로컬 blob 표시라 불필요). 정직: 서명값의 실제 수용은 샌드박스가 R2를 차단해 증명 불가 — 검증 사다리 3번(실기기 업로드)이 유일한 결정적 증명.',
  },
];
