// GENERATED by scripts/gen-sync-release-contract.mjs — do not edit.
// SSOT: schemas/sync-release-contract.json
export const SYNC_RELEASE_CONTRACT = {
  "schemaVersion": 1,
  "mediaSign": {
    "protocolVersion": 7,
    "requiredOps": [
      "probe",
      "capabilities",
      "list",
      "put",
      "get",
      "delete",
      "deleteMany",
      "abortMultipart"
    ],
    "sourceSha256": "58aeb062486b90318ed321fc027c47249f2029eab6f082e9b33eeb67131806ba"
  },
  "runtime": {
    "stallAfterMs": 300000
  }
} as const;
