// GENERATED by scripts/gen-sync-release-contract.mjs — do not edit.
// SSOT: schemas/sync-release-contract.json
export const SYNC_RELEASE_CONTRACT = {
  "schemaVersion": 1,
  "mediaSign": {
    "protocolVersion": 8,
    "requiredOps": [
      "probe",
      "capabilities",
      "list",
      "put",
      "get",
      "delete",
      "deleteMany",
      "abortMultipart"
    ],
    "sourceSha256": "1619d7cfd519e60ddf5e58db9463ebb382838e7bf29f8eeaceaf2466d35ead38"
  },
  "runtime": {
    "stallAfterMs": 300000
  }
} as const;
